[package]
name = "typefast"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.3"
dirs = "5.0.1"
thiserror = "2.0.9"
rand = "0.8.5"
rusqlite = { version = "0.31.0", features = ["bundled"] }
chrono = "0.4.39"
